
server:
  #tomcat最大线程数，默认为200
  max-threads: 800
  # Tomcat启动初始化的线程数，默认值25
  min-spare-threads: 30
  #服务器的HTTP端口，默认为8080
  port: 8001
  servlet:
    #应用的访问路径
    context-path: /url-shortcut
  tomcat:
    #tomcat的URI编码
    uri-encoding: UTF-8

# Spring配置 
spring:
  messages:
    # 资源信息 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      # 文件上传单个文件大小
      max-file-size: 10MB
      # 文件上传设置总上传的文件大小
      max-request-size: 20MB
  datasource:
    ##spring数据源配置
    driver-class-name: org.postgresql.Driver
    password: peak1203
    url: jdbc:postgresql://106.13.203.73:5432/url_shortcut?setUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: postgres
  # redis 配置
  redis:
    # 地址
    host: 106.13.203.73
    # 密码
    password: 123456
    # 数据库索引
    database: 0
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10S
    # 连接池
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        m-idle: 0
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
  
ynfy:
  path:
    # 文件访问api
    accessPath: /api/**
    localPath: ${config.swaggerEnabled}
  thread:
    # 核心线程池大小
    corePoolSize: 10
    # 最大可创建的线程数
    maxPoolSize: 30
    # 队列最大长度
    queueCapacity: 100
    # 线程池维护线程所允许的空闲时间
    keepAliveSeconds: 60